[package]
name = "gear"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"    # custom hasher that is much more performant for small keys
paste = "1.0.14" # allows identifiers to be pasted together within macros
